export const USER_LOGIN = "USER_LOGIN";
export const ADD_CORPORATE = "ADD_CORPORATE";
export const UPDATE_CORPORATE = "UPDATE_CORPORATE";
export const ALL_CORPORATE = "ALL_CORPORATE";
export const SINGLE_CORPORATE = "SINGLE_CORPORATE";

